# Generated by Django 5.0.6 on 2024-07-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('key', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('value', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Dados de Configurações Extra',
                'verbose_name_plural': 'Dados de Configurações Extra',
                'db_table': 'dados_config',
                'ordering': ['key'],
            },
        ),
    ]
